#!/usr/bin/env bash
# In-VM validation for the *feature/stage-coverage* e2e descriptors (kept separate
# from the disk-layout asserter, lib/validate.sh). It runs as the user on the
# installed system after `archwright bootstrap` and checks each feature named in
# EXPECT_FEATURES (a space-separated token list injected via expect.env). Same
# contract as validate.sh: "OK:" / "FAIL:" lines and a non-zero exit on any fail.
#
# Tokens (add one when you add a feature descriptor):
#   reflector    mirrorlist was regenerated by reflector (Phase A)
#   kernel-zen   the linux-zen custom kernel installed + set default (Phase A)
#   plymouth     plymouth default theme set to spinner
#   hooks        the lifecycle/per-stage hook markers were created
#   setup        the setup-stage git clone landed
#   services     the enabled systemd unit (fstrim.timer) is enabled
#   dotfiles     the dotfiles manager applied (marker dotfile present)
#   flatpak      the configured flatpak app is installed
#   desktop      the KDE stage wrote look&feel/color config
#   repos        the custom repo's signing key is in the pacman keyring
set -uo pipefail

fails=0
ok()   { echo "OK: $*"; }
fail() { echo "FAIL: $*"; fails=$((fails + 1)); }

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
[[ -f "$HERE/expect.env" ]] && source "$HERE/expect.env"
: "${EXPECT_FEATURES:=}"

echo "=== e2e feature validation: [$EXPECT_FEATURES] ==="

for feat in $EXPECT_FEATURES; do
	case "$feat" in
	reflector)
		# reflector --save writes a "# … reflector …" header into the mirrorlist.
		grep -qi 'reflector' /etc/pacman.d/mirrorlist \
			&& ok "mirrorlist generated by reflector" || fail "mirrorlist has no reflector header"
		;;
	kernel-zen)
		[[ -e /boot/vmlinuz-linux-zen ]] && ok "linux-zen kernel image present" || fail "/boot/vmlinuz-linux-zen missing"
		pacman -Q linux-zen >/dev/null 2>&1 && ok "linux-zen package installed" || fail "linux-zen not installed"
		# kernel.default linux-zen -> grub default menuentry references it.
		if [[ -f /boot/grub/grub.cfg ]]; then
			grep -q 'linux-zen' /boot/grub/grub.cfg && ok "grub.cfg references linux-zen" || fail "grub.cfg has no linux-zen entry"
		fi
		;;
	plymouth)
		if [[ -f /etc/plymouth/plymouthd.conf ]] && grep -qi '^\s*Theme\s*=\s*spinner' /etc/plymouth/plymouthd.conf; then
			ok "plymouth default theme is spinner"
		else
			# Fall back to the tool's own view of the default theme.
			[[ "$(plymouth-set-default-theme 2>/dev/null)" == "spinner" ]] \
				&& ok "plymouth default theme is spinner" || fail "plymouth theme not set to spinner"
		fi
		;;
	hooks)
		for f in "$HOME/e2e-pre-bootstrap" "$HOME/e2e-post-bootstrap" \
		         "$HOME/e2e-before-packages" "$HOME/e2e-after-packages"; do
			[[ -f "$f" ]] && ok "hook marker $(basename "$f")" || fail "missing hook marker $f"
		done
		[[ -f /e2e-root-hook ]] && ok "root hook marker /e2e-root-hook" || fail "missing root hook marker /e2e-root-hook"
		;;
	setup)
		[[ -d "$HOME/e2e-clone/.git" ]] && ok "setup-stage clone present" || fail "setup clone ~/e2e-clone missing"
		;;
	services)
		st="$(systemctl is-enabled fstrim.timer 2>/dev/null)"
		[[ "$st" == "enabled" ]] && ok "fstrim.timer enabled" || fail "fstrim.timer not enabled (got '$st')"
		;;
	dotfiles)
		# Pass if a controlled repo applied its marker, OR (repo-agnostic) the
		# manager cloned its source tree — proves the dotfiles stage ran.
		if [[ -f "$HOME/.e2e-dotfile" ]]; then
			ok "dotfiles applied (~/.e2e-dotfile)"
		elif [[ -d "$HOME/.local/share/chezmoi/.git" || -d "$HOME/.dotfiles" || -d "$HOME/.local/share/yadm/repo.git" ]]; then
			ok "dotfiles source cloned by the manager"
		else
			fail "no dotfiles applied/cloned"
		fi
		;;
	flatpak)
		if flatpak list --columns=application 2>/dev/null | grep -q "${EXPECT_FLATPAK_APP:-}"; then
			ok "flatpak app ${EXPECT_FLATPAK_APP:-} installed"
		else
			fail "flatpak app ${EXPECT_FLATPAK_APP:-} not installed"
		fi
		;;
	desktop)
		# The KDE stage runs plasma-apply-* (look&feel/colorscheme). Headless, with
		# no running plasma session, those may not persist to ~/.config/kdeglobals,
		# so asserting the applied scheme is unreliable. What we CAN verify is that
		# the stage's prerequisites are installed and the tools are present (the
		# stage having run without error is already gated by E2E_BOOTSTRAP_RC=0).
		# If kdeglobals did get written, assert the scheme too (best-effort).
		if command -v plasma-apply-colorscheme >/dev/null 2>&1; then
			ok "plasma-apply tools present (KDE stage ran)"
		else
			fail "plasma-apply-colorscheme missing (plasma not installed)"
		fi
		if grep -qi "${EXPECT_KDE_COLORSCHEME:-BreezeDark}" "$HOME/.config/kdeglobals" 2>/dev/null; then
			ok "KDE color scheme persisted to kdeglobals"
		fi
		;;
	repos)
		if sudo pacman-key --list-keys "${EXPECT_REPO_KEY:-}" >/dev/null 2>&1; then
			ok "repo signing key ${EXPECT_REPO_KEY:-} in keyring"
		else
			fail "repo key ${EXPECT_REPO_KEY:-} not in keyring"
		fi
		;;
	*)
		fail "unknown feature token: $feat"
		;;
	esac
done

echo "=== feature validation complete: $fails failure(s) ==="
exit $((fails > 0 ? 1 : 0))
