#!/usr/bin/env bash
# In-VM validation, run as the user on the *installed* system after `archwright
# bootstrap`. Expectations are injected as EXPECT_* env vars (see expect.env,
# generated by the orchestrator from the matrix descriptor) so this one script
# covers every layout — it asserts the things that must be true regardless of
# config, plus the layout-conditional ones gated on EXPECT_LAYOUT.
#
# It prints "OK: ..." per passing check and "FAIL: ..." per failure, and exits
# non-zero if any check failed. The orchestrator keys off the exit code (relayed
# through e2e-bootstrap.sh's E2E_VALIDATE_RC marker).
set -uo pipefail

fails=0
ok()   { echo "OK: $*"; }
fail() { echo "FAIL: $*"; fails=$((fails + 1)); }

# Source the expectations written next to this script.
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
[[ -f "$HERE/expect.env" ]] && source "$HERE/expect.env"

: "${EXPECT_LAYOUT:=lvm}"
: "${EXPECT_ROOT_FS:=}"
: "${EXPECT_SWAP:=swapfile}"
: "${EXPECT_BOOTLOADER:=grub}"
: "${EXPECT_HOSTNAME:=}"
: "${EXPECT_USER:=}"
: "${EXPECT_VG:=}"
: "${EXPECT_LV:=}"
: "${EXPECT_PV_COUNT:=}"
: "${EXPECT_PACKAGES:=}"
: "${EXPECT_AUR_HELPER:=yay}"
: "${EXPECT_ENCRYPTION:=0}"

echo "=== e2e validation (layout=$EXPECT_LAYOUT fs=$EXPECT_ROOT_FS swap=$EXPECT_SWAP bootloader=$EXPECT_BOOTLOADER) ==="

# --- root filesystem -------------------------------------------------------
root_src="$(findmnt -n -o SOURCE /)"
root_fstype="$(findmnt -n -o FSTYPE /)"
[[ -n "$root_src" ]] && ok "root mounted from $root_src ($root_fstype)" || fail "root not mounted"
if [[ -n "$EXPECT_ROOT_FS" ]]; then
	[[ "$root_fstype" == "$EXPECT_ROOT_FS" ]] && ok "root fstype is $EXPECT_ROOT_FS" \
		|| fail "root fstype expected $EXPECT_ROOT_FS, got $root_fstype"
fi

# --- ESP at /boot ----------------------------------------------------------
boot_fstype="$(findmnt -n -o FSTYPE /boot 2>/dev/null || true)"
[[ "$boot_fstype" == "vfat" ]] && ok "/boot is vfat (ESP)" || fail "/boot expected vfat, got '${boot_fstype:-<none>}'"

# --- layout-specific -------------------------------------------------------
case "$EXPECT_LAYOUT" in
lvm)
	if [[ -n "$EXPECT_VG" ]]; then
		sudo vgs --noheadings -o vg_name 2>/dev/null | tr -d ' ' | grep -qx "$EXPECT_VG" \
			&& ok "VG $EXPECT_VG exists" || fail "VG $EXPECT_VG not found"
	fi
	if [[ -n "$EXPECT_LV" ]]; then
		sudo lvs --noheadings -o lv_name "$EXPECT_VG" 2>/dev/null | tr -d ' ' | grep -qx "$EXPECT_LV" \
			&& ok "LV $EXPECT_LV exists in $EXPECT_VG" || fail "LV $EXPECT_LV not found"
	fi
	if [[ -n "$EXPECT_PV_COUNT" ]]; then
		n="$(sudo vgs --noheadings -o pv_count "$EXPECT_VG" 2>/dev/null | tr -d ' ')"
		[[ "$n" == "$EXPECT_PV_COUNT" ]] && ok "VG $EXPECT_VG has $n PV(s)" \
			|| fail "VG $EXPECT_VG expected $EXPECT_PV_COUNT PVs, got '$n'"
	fi
	;;
btrfs)
	[[ "$root_fstype" == "btrfs" ]] && ok "root is btrfs" || fail "root expected btrfs, got $root_fstype"
	subs="$(sudo btrfs subvolume list / 2>/dev/null | wc -l)"
	[[ "$subs" -ge 1 ]] && ok "btrfs has $subs subvolume(s)" || fail "no btrfs subvolumes found"
	;;
plain)
	# root_src should be a bare partition (no dm/lvm mapper).
	[[ "$root_src" == /dev/* && "$root_src" != /dev/mapper/* ]] \
		&& ok "plain root on partition $root_src" || fail "plain root unexpected source $root_src"
	;;
esac

# --- swap ------------------------------------------------------------------
swap_active="$(swapon --show=NAME --noheadings 2>/dev/null | head -1)"
case "$EXPECT_SWAP" in
swapfile)
	swapon --show 2>/dev/null | grep -q '/swapfile' && ok "swapfile active" || fail "swapfile not active"
	;;
partition)
	[[ -n "$swap_active" ]] && ok "swap partition active ($swap_active)" || fail "no active swap"
	;;
zram)
	if zramctl 2>/dev/null | grep -qi '\[SWAP\]\|zram'; then ok "zram present"; else
		[[ -n "$swap_active" ]] && ok "swap active ($swap_active)" || fail "zram/swap not active"
	fi
	;;
none)
	[[ -z "$swap_active" ]] && ok "no swap (as configured)" || fail "swap active but expected none ($swap_active)"
	;;
esac

# --- bootloader ------------------------------------------------------------
case "$EXPECT_BOOTLOADER" in
grub)
	[[ -f /boot/grub/grub.cfg ]] && ok "grub.cfg present" || fail "/boot/grub/grub.cfg missing"
	;;
systemd-boot)
	if sudo bootctl is-installed >/dev/null 2>&1; then ok "systemd-boot installed"; else
		[[ -d /boot/loader/entries ]] && ok "systemd-boot loader entries present" || fail "systemd-boot not detected"
	fi
	;;
esac

# --- user + groups ---------------------------------------------------------
if [[ -n "$EXPECT_USER" ]]; then
	id "$EXPECT_USER" >/dev/null 2>&1 && ok "user $EXPECT_USER exists" || fail "user $EXPECT_USER missing"
	id -nG "$EXPECT_USER" 2>/dev/null | tr ' ' '\n' | grep -qx wheel \
		&& ok "user $EXPECT_USER in wheel" || fail "user $EXPECT_USER not in wheel"
fi

# --- hostname --------------------------------------------------------------
if [[ -n "$EXPECT_HOSTNAME" ]]; then
	hn="$(cat /etc/hostname 2>/dev/null)"
	[[ "$hn" == "$EXPECT_HOSTNAME" ]] && ok "hostname is $EXPECT_HOSTNAME" || fail "hostname expected $EXPECT_HOSTNAME, got '$hn'"
fi

# --- AUR helper (installed by the yay stage) -------------------------------
if [[ -n "$EXPECT_AUR_HELPER" ]]; then
	command -v "$EXPECT_AUR_HELPER" >/dev/null 2>&1 \
		&& ok "AUR helper $EXPECT_AUR_HELPER installed" || fail "AUR helper $EXPECT_AUR_HELPER not on PATH"
fi

# --- Phase B packages ------------------------------------------------------
for p in $EXPECT_PACKAGES; do
	pacman -Q "$p" >/dev/null 2>&1 && ok "package $p installed" || fail "package $p not installed"
done

echo "=== validation complete: $fails failure(s) ==="
exit $((fails > 0 ? 1 : 0))
